### ISSUE TITLE
New SWID international standard

### ISSUE THREAD

**Issue by henryean** [Labs64/swid-generator#3]
The international standard for SWID tags has been updated to: [ISO/IEC 19770-2:2015](https://www.iso.org/standard/65666.html).

Are there any plans to update this project to use the new standards?

**Comment by r-brown** [comment]
Hello @henryean thank you for suggestion here.
We observe a very low adoption of the SWID format in general.

Would you have a use case here?

**Comment by henryean** [comment]
I have a client who wants to generate SWID tags for all applications/microservices in their architecture to use for registering which applications are present on all servers. I had hoped that I could use the maven plugin that you made, but it uses the older standard.

**Comment by r-brown** [comment]
Hello @henryean - would you ming to contribute here and use the current library as a baseline and implement new SWID standard.
We will be happy to state you as a contributor on the main page after successful pull request.

**Comment by henryean** [comment]
Hello @r-brown - I have made a start reworking the swid-generator and the maven plugin with the new standard. Once I have something that looks workable. I will check it in for comments. :)

**Comment by henryean** [comment]
Hello @r-brown , do I need permission to push commits to this repository? I cloned the repository and have made a branch, but I get a 403 when I try to push.

**Comment by r-brown** [comment]
Hello @henryean you can create a [Pull Request](https://github.com/Labs64/swid-generator/compare) - this can be done easily using GitHub.

**Comment by henryean** [comment]
I've made the pull request. It's not linked yet to this issue.

**Comment by r-brown** [comment]
fixed by #4
